# Generated by Django 5.0.7 on 2024-07-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0001_initial'),
        ('room', '0003_alter_room_options_remove_room_host_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Topic.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
