# Generated by Django 5.0.7 on 2024-07-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_topic_delete_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
