# Generated by Django 5.0.7 on 2024-07-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
